#------------------------------------------------------------------------------------------------------------------------
#
# docker-compose -f "docker-compose.yml" -f "docker-compose.override.yml" up -d --no-recreate bet.hosting
#
# docker-compose -f "docker-compose.yml"  up  -d --no-recreate bet.hosting
#------------------------------------------------------------------------------------------------------------------------

version: '3.4'

services:
  bet.web:
    image: ${DOCKER_REGISTRY-}/bet:web
    build:
      context: .
      dockerfile: src/Bet.AspNetCore.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        NUGET_RESTORE: "-v=m" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.AspNetCore.Sample/Bet.AspNetCore.Sample.csproj"
        SOLUTION_BASE: "false"

  bet.k8sweb:
    image: ${DOCKER_REGISTRY-}/bet:k8sweb
    build:
      context: .
      dockerfile: src/Bet.K8s.Web.Sample/Dockerfile
      args:
        RUNTESTS: "false"
        VERBOSE: "false"
        NUGET_RESTORE: "-v=m" #overides the --disable-parallel
        PROJECT_PATH: "/src/Bet.K8s.Web.Sample/Bet.K8s.Web.Sample.csproj"
        SOLUTION_BASE: "false"
